spring:
  profiles:
    active: local

  datasource:
#    url: jdbc:h2:mem:homepage;MODE=MySQL;
    url: jdbc:h2:tcp://localhost/~/homepage;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb

    hibernate:
      ddl-auto: create

  session:
    store-type: jdbc

logging.level:
  org.hibernate.SQL: debug

origin: "http://localhost:3000"

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: gksrbdus
    key-alias: tomcat
  port: 8443
  http2:
    enabled: true


