spring:
  profiles:
    include: prod-db

  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb

  session:
    store-type: jdbc

origin: "http://localhost:3000"

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: gksrbdus
    key-alias: tomcat
  port: 8443
  http2:
    enabled: true


