spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:homepage;MODE=MySQL;
    #    url: jdbc:h2:tcp://localhost/~/homepage
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb

    hibernate:
      ddl-auto: update

  session:
    store-type: jdbc

logging.level:
  org.hibernate.SQL: debug

